version: '3.9'

services:
  payment:
    image: payment-api:latest
    build:
      context: .
      dockerfile: ./dockerfile/Dockerfile-local
    ports:
      - "3003:8003"
    environment:
      - PORT=8003
    restart: always
    networks:
      - msa-api-network

networks:
  msa-api-network: